service: default
runtime: python27
api_version: 1
threadsafe: true
env: standard
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: ssl
  version: latest
- name: PIL
  version: latest

env_variables:
  # The app will look for the model file at: gs://MODEL_BUCKET/MODEL_FILENAME
  MODEL_BUCKET: color-wave-bucket
  MODEL_FILENAME: lr.pkl